name: Quality Checks
on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.28
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run coverage tool
        uses: anz-bank/go-acc@v0.11.0
        with:
          soft_target: 87
          hard_target: 80
